### PR TITLE
Add Polish translation

### PR DESCRIPTION
**Pull request by temp-byte**

### CODE REVIEW

**Comment by xxxcucus** [comment]
Thank you for the traslation. In order to complete the translation please create a folder pl in the fastlane/metadata/android folder and in the folder add two files full_description.txt and short_description.txt In these two files translate the contents of the two corresponding files from the folder fastlane/metadata/android/en-US folder.

**Comment by temp-byte** [comment]
Done.

**Comment by temp-byte** [comment]
> Thank you for the traslation. In order to complete the translation please create a folder pl in the fastlane/metadata/android folder and in the folder add two files full_description.txt and short_description.txt In these two files translate the contents of the two corresponding files from the folder fastlane/metadata/android/en-US folder.

Done.

**Comment by xxxcucus** [comment]
The following texts from strings.xml need to be translated as well.

    <string name="positioningplanestutorial">Positioning of Planes Tutorial</string>
    <string name="guessingplanestutorial">Guessing of Planes Tutorial</string>

    <string name="savesettings">Save Preferences</string>
    <string name="game">Game</string>
    <string name="videos">Videos</string>
    <string name="about">About</string>
    <string name="helptext_videos1">Touch on the playlist title to play video.</string>
    <string name="helptext_videos2">Touch on the playlist title of the playing video to start video from beginning.</string>
    <string name="helptext_videos3">Long touch on the playlist title to play video in the Youtube App. </string>
    <string name="credits_othercontributions_title">Other Contributions</string>
    <string name="credits_othercontributions">Other contributions to the project are from: Mihai Birau, Stefan Luchian, Dan Ilies, Stefan Cucu, Christian von der Ehe, Pascal Seeger and Mario Eduardo Zarate Caceres.</string>
    <string name="credits_tools_title">Tools</string>
    <string name="credits_tools">We thank the company JetBrains for the free software licenses for tools used when programming the project.</string>
    <string name="software_version_title">Version</string>
    <string name="software_version">The current version of the software is </string>

**Comment by temp-byte** [comment]
@xxxcucus I seem to be missing the strings you quoted.

**Comment by xxxcucus** [comment]
I think you have an old version of the master branch.

**Comment by xxxcucus** [comment]
PR was merged. Thanks! Would you leave me your email address as I would require further translations later this year ?

**Comment by temp-byte** [comment]
@xxxcucus Here, you can use this one w30kat7c6@mozmail.com

**Pull request merged**
