### PR TITLE
Remade Login and Register Layout to match Material Design.

### PR DESCRIPTION
**Pull request by Tc2r1**

### CODE REVIEW

**Comment by xxxcucus** [comment]
Thank you for your contributions.
I will have to look at this in more detail as I am not familiar with material design.

**Comment by Tc2r1** [comment]
Hey @xxxcucus  could you please approve these asap as the timer for acceptance doesn't start until you do and there is a limited number of shirts for hacktoberfest first come first serve lol. I figured I'd help out your repo since your repo helped my brother @androidlion48 get more experience with learning AS. I'm a senior dev and he's learning, thanks. 

Please merge his first, then do mine (which will overwrite one of his prs, the one where he added a button to go to registration screen).  I saw you comment about end of week, I fear that may be too late lol :D thanks. 

Ps I've love talk w you on how you ported a java game into AS and built the app around it. I made a java game years ago I wish I could port, didnt think it was possible until now.

**Comment by xxxcucus** [comment]
I have just merged two of his and two of yours. I hope it was not too late for the T-Shirts. For the last one I am not sure yet. It will have to wait until I have time to check it.

**Comment by xxxcucus** [comment]
I have created a branch called material_design_1. Please make a PR with your changes in this PR for this branch and I will merge. This is because  I want to study this carefully before integrating it in my projects.

**Comment by Tc2r1** [comment]
@xxxcucus  done :D Please don't too long to merge and have a great weekend.

**Comment by Tc2r1** [comment]
Please add the lable #Hacktoberfest-accepted as this one isn't being tracked properly :(

**Comment by xxxcucus** [comment]
I am preparing a new release and would like to mention you and your brother as contributors. Could you please leave me your email address such that we can communicate ?

**Pull request merged**
